import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'app.title': 'Church Kids Management',
    'app.subtitle': 'A comprehensive system for managing church children activities',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.date': 'Date',
    'common.notes': 'Notes',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.present': 'Present',
    'common.absent': 'Absent',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.saving': 'Saving...',
    'common.noData': 'No data available',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.signout': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.phoneNumber': 'Phone Number',
    'auth.loginDescription': 'Enter your credentials to access your account',
    'auth.signupDescription': 'Create an account to get started',
    'auth.loggingIn': 'Logging in...',
    'auth.creatingAccount': 'Creating account...',
    
    // Index/Landing
    'landing.getStarted': 'Get Started',
    'landing.features': 'Features',
    'landing.childrenManagement': 'Children Management',
    'landing.childrenManagementDesc': 'Register and manage children profiles with parent information and attendance history.',
    'landing.attendanceTracking': 'Attendance Tracking',
    'landing.attendanceTrackingDesc': 'Track attendance for each service with easy check-in and detailed records.',
    'landing.reportsAnalytics': 'Reports & Analytics',
    'landing.reportsAnalyticsDesc': 'Generate comprehensive reports on attendance patterns and trends.',
    'landing.roleBasedAccess': 'Role-Based Access',
    'landing.roleBasedAccessDesc': 'Different access levels for administrators, servants, and parents.',
    'landing.forAdmins': 'For Administrators',
    'landing.forAdminsDesc': 'Full system control, manage all users, children, and generate reports.',
    'landing.forServants': 'For Servants/Teachers',
    'landing.forServantsDesc': 'Record attendance, view assigned children, and communicate with parents.',
    'landing.forParents': 'For Parents',
    'landing.forParentsDesc': 'View your children\'s attendance records and receive notifications.',
    'landing.systemBenefits': 'System Benefits',
    'landing.benefit1': 'Real-time attendance tracking',
    'landing.benefit2': 'Automated absence notifications',
    'landing.benefit3': 'Comprehensive reporting',
    'landing.benefit4': 'Secure data management',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.title': 'Dashboard',
    'dashboard.noRole': 'No role assigned. Please contact an administrator.',
    'dashboard.manageChildren': 'Manage Children',
    'dashboard.manageChildrenDesc': 'Add, edit, and view all registered children',
    'dashboard.manageServants': 'Manage Servants',
    'dashboard.manageServantsDesc': 'View and manage servant accounts',
    'dashboard.recordAttendance': 'Record Attendance',
    'dashboard.recordAttendanceDesc': 'Take attendance for today\'s service',
    'dashboard.viewReports': 'View Reports',
    'dashboard.viewReportsDesc': 'Generate and view attendance reports',
    'dashboard.absentChildren': 'Absent Children',
    'dashboard.absentChildrenDesc': 'View and notify parents of absent children',
    'dashboard.manageRoles': 'Manage Roles',
    'dashboard.manageRolesDesc': 'Assign and manage user roles',
    'dashboard.qrCodes': 'QR Codes',
    'dashboard.qrCodesDesc': 'Generate QR codes for children',
    'dashboard.scanQR': 'Scan QR',
    'dashboard.scanQRDesc': 'Scan QR codes to record attendance',
    'dashboard.myChildren': 'My Children',
    'dashboard.myChildrenDesc': 'View your children\'s information',
    'dashboard.attendanceHistory': 'Attendance History',
    'dashboard.attendanceHistoryDesc': 'View attendance records for your children',
    'dashboard.servantAttendance': 'Servant Attendance',
    'dashboard.servantAttendanceDesc': 'Record attendance for servants',
    
    // Children
    'children.title': 'Children Management',
    'children.addNew': 'Add New Child',
    'children.editChild': 'Edit Child',
    'children.noChildren': 'No children found',
    'children.fullName': 'Full Name',
    'children.dateOfBirth': 'Date of Birth',
    'children.parentName': 'Parent Name',
    'children.parentPhone': 'Parent Phone',
    'children.address': 'Address',
    'children.schoolGrade': 'School Grade',
    'children.attendanceStatus': 'Attendance Status',
    'children.assignedServant': 'Assigned Servant',
    'children.selectServant': 'Select Servant',
    'children.noServant': 'No Servant Assigned',
    'children.formDescription': 'Enter the child\'s information below',
    'children.regular': 'Regular',
    'children.irregular': 'Irregular',
    'children.new': 'New',
    'children.confirmDelete': 'Are you sure you want to delete this child?',
    
    // Servants
    'servants.title': 'Servants Management',
    'servants.noServants': 'No servants found',
    
    // Servant Attendance
    'servantAttendance.title': 'Servant Attendance',
    'servantAttendance.subtitle': 'Record attendance for servants',
    'servantAttendance.selectDate': 'Select Service Date',
    'servantAttendance.presentCount': 'Present',
    'servantAttendance.absentCount': 'Absent',
    'servantAttendance.totalCount': 'Total Servants',
    'servantAttendance.saveSuccess': 'Servant attendance saved successfully',
    'servantAttendance.saveError': 'Failed to save servant attendance',
    'servantAttendance.loadError': 'Failed to load servants',
    'servantAttendance.noServants': 'No servants registered',
    
    // Attendance
    'attendance.title': 'Attendance',
    'attendance.selectDate': 'Select Date',
    'attendance.recordedBy': 'Recorded by',
    'attendance.markPresent': 'Mark Present',
    'attendance.markAbsent': 'Mark Absent',
    'attendance.alreadyRecorded': 'Attendance already recorded',
    'attendance.saveSuccess': 'Attendance saved successfully',
    'attendance.saveError': 'Failed to save attendance',
    'attendance.presentCount': 'Present',
    'attendance.absentCount': 'Absent',
    'attendance.totalCount': 'Total',
    
    // Reports
    'reports.title': 'Reports & Statistics',
    'reports.generate': 'Generate Report',
    'reports.dateRange': 'Date Range',
    'reports.startDate': 'Start Date',
    'reports.endDate': 'End Date',
    'reports.totalChildren': 'Total Children',
    'reports.registeredInSystem': 'Registered in the system',
    'reports.averageAttendance': 'Average Attendance',
    'reports.acrossAllChildren': 'Across all children',
    'reports.totalRecords': 'Total Records',
    'reports.attendanceRecords': 'Attendance records',
    'reports.individualStats': 'Individual Attendance Statistics',
    'reports.detailedBreakdown': 'Detailed attendance breakdown for each child',
    'reports.childName': 'Child Name',
    'reports.totalServices': 'Total Services',
    'reports.attended': 'Attended',
    'reports.attendanceRate': 'Attendance Rate',
    'reports.noData': 'No attendance data available yet',
    'reports.loadError': 'Failed to load reports',
    
    // Absent Children
    'absentChildren.title': 'Absent Children Report',
    'absentChildren.subtitle': 'View and notify parents of absent children',
    'absentChildren.allAttended': 'All children attended on this date',
    'absentChildren.absentCount': 'children were absent',
    'absentChildren.noAbsent': 'No absent children for this date',
    'absentChildren.sendWhatsApp': 'Send WhatsApp to',
    'absentChildren.parents': 'Parents',
    'absentChildren.sending': 'Sending...',
    'absentChildren.childName': 'Child Name',
    'absentChildren.parentName': 'Parent Name',
    'absentChildren.parentPhone': 'Parent Phone',
    'absentChildren.noPermission': 'You don\'t have permission to access this page',
    'absentChildren.loadError': 'Failed to load absent children',
    'absentChildren.notifySuccess': 'Successfully sent WhatsApp notifications',
    'absentChildren.notifyPartialError': 'Failed to send some notifications',
    'absentChildren.noChildren': 'No absent children to notify',
    
    // Child Report
    'childReport.title': 'Child Profile Report',
    'childReport.generatedOn': 'Generated on',
    'childReport.personalInfo': 'Personal Information',
    'childReport.fullName': 'Full Name',
    'childReport.dateOfBirth': 'Date of Birth',
    'childReport.yearsOld': 'years old',
    'childReport.schoolGrade': 'School Grade',
    'childReport.notSpecified': 'Not specified',
    'childReport.status': 'Status',
    'childReport.active': 'Active',
    'childReport.address': 'Address',
    'childReport.parentName': 'Parent Name',
    'childReport.parentPhone': 'Parent Phone',
    'childReport.registrationDate': 'Registration Date',
    'childReport.generalNotes': 'General Notes',
    'childReport.attendanceSummary': 'Attendance Summary',
    'childReport.totalSessions': 'Total Sessions',
    'childReport.attendanceHistory': 'Attendance History',
    'childReport.noRecords': 'No attendance records found',
    'childReport.endOfReport': 'End of Report',
    'childReport.print': 'Print',
    'childReport.exportPDF': 'Export PDF',
    'childReport.backToChildren': 'Back to Children',
    'childReport.notFound': 'Child not found',
    'childReport.loadingReport': 'Loading report...',
    'childReport.loadError': 'Failed to load child report',
    'childReport.exportHint': 'Use Print > Save as PDF to export the report',
    
    // Manage Roles
    'manageRoles.title': 'Manage User Roles',
    'manageRoles.subtitle': 'Assign roles to users to control their access level',
    'manageRoles.roleDescriptions': 'Role Descriptions:',
    'manageRoles.adminDesc': 'Full access to all features',
    'manageRoles.servantDesc': 'Can manage assigned children and record attendance',
    'manageRoles.parentDesc': 'Can view their child\'s information and attendance',
    'manageRoles.currentRole': 'Current Role',
    'manageRoles.changeRole': 'Change Role',
    'manageRoles.noRole': 'No role',
    'manageRoles.noUsers': 'No users found',
    'manageRoles.roleUpdated': 'Role updated successfully',
    'manageRoles.roleRemoved': 'Role removed successfully',
    'manageRoles.updateError': 'Unable to update role. Please try again.',
    'manageRoles.loadError': 'Unable to load users. Please refresh the page.',
    'manageRoles.adminOnly': 'Only administrators can manage roles',
    'manageRoles.manualSetup': 'Manual Setup (Alternative Method)',
    'manageRoles.manualSetupDesc': 'If you need to manually set roles via the backend',
    
    // QR
    'qr.title': 'QR Codes',
    'qr.generate': 'Generate QR Code',
    'qr.download': 'Download',
    'qr.print': 'Print',
    'qr.scanTitle': 'QR Scanner',
    'qr.scanInstructions': 'Point your camera at a QR code to scan',
    'qr.scanSuccess': 'Attendance recorded successfully',
    'qr.scanError': 'Error scanning QR code',
    
    // Roles
    'roles.title': 'Manage Roles',
    'roles.admin': 'Admin',
    'roles.servant': 'Servant',
    'roles.parent': 'Parent',
    'roles.none': 'No Role',
    'roles.assignRole': 'Assign Role',
    'roles.currentRole': 'Current Role',
  },
  ar: {
    // Common
    'app.title': 'إدارة أطفال الكنيسة',
    'app.subtitle': 'نظام شامل لإدارة أنشطة أطفال الكنيسة',
    'common.loading': 'جاري التحميل...',
    'common.back': 'رجوع',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.date': 'التاريخ',
    'common.notes': 'ملاحظات',
    'common.actions': 'الإجراءات',
    'common.status': 'الحالة',
    'common.present': 'حاضر',
    'common.absent': 'غائب',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.saving': 'جاري الحفظ...',
    'common.noData': 'لا توجد بيانات',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.signout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.phoneNumber': 'رقم الهاتف',
    'auth.loginDescription': 'أدخل بياناتك للوصول إلى حسابك',
    'auth.signupDescription': 'أنشئ حساباً للبدء',
    'auth.loggingIn': 'جاري تسجيل الدخول...',
    'auth.creatingAccount': 'جاري إنشاء الحساب...',
    
    // Index/Landing
    'landing.getStarted': 'ابدأ الآن',
    'landing.features': 'المميزات',
    'landing.childrenManagement': 'إدارة الأطفال',
    'landing.childrenManagementDesc': 'تسجيل وإدارة ملفات الأطفال مع معلومات أولياء الأمور وسجل الحضور.',
    'landing.attendanceTracking': 'تتبع الحضور',
    'landing.attendanceTrackingDesc': 'تتبع الحضور لكل خدمة مع تسجيل سهل وسجلات مفصلة.',
    'landing.reportsAnalytics': 'التقارير والتحليلات',
    'landing.reportsAnalyticsDesc': 'إنشاء تقارير شاملة عن أنماط واتجاهات الحضور.',
    'landing.roleBasedAccess': 'صلاحيات حسب الدور',
    'landing.roleBasedAccessDesc': 'مستويات وصول مختلفة للمسؤولين والخدام وأولياء الأمور.',
    'landing.forAdmins': 'للمسؤولين',
    'landing.forAdminsDesc': 'تحكم كامل بالنظام، إدارة جميع المستخدمين والأطفال وإنشاء التقارير.',
    'landing.forServants': 'للخدام/المعلمين',
    'landing.forServantsDesc': 'تسجيل الحضور، عرض الأطفال المعينين، والتواصل مع أولياء الأمور.',
    'landing.forParents': 'لأولياء الأمور',
    'landing.forParentsDesc': 'عرض سجلات حضور أطفالك وتلقي الإشعارات.',
    'landing.systemBenefits': 'فوائد النظام',
    'landing.benefit1': 'تتبع الحضور في الوقت الفعلي',
    'landing.benefit2': 'إشعارات الغياب التلقائية',
    'landing.benefit3': 'تقارير شاملة',
    'landing.benefit4': 'إدارة بيانات آمنة',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.noRole': 'لم يتم تعيين دور. يرجى الاتصال بالمسؤول.',
    'dashboard.manageChildren': 'إدارة الأطفال',
    'dashboard.manageChildrenDesc': 'إضافة وتعديل وعرض جميع الأطفال المسجلين',
    'dashboard.manageServants': 'إدارة الخدام',
    'dashboard.manageServantsDesc': 'عرض وإدارة حسابات الخدام',
    'dashboard.recordAttendance': 'تسجيل الحضور',
    'dashboard.recordAttendanceDesc': 'تسجيل الحضور لخدمة اليوم',
    'dashboard.viewReports': 'عرض التقارير',
    'dashboard.viewReportsDesc': 'إنشاء وعرض تقارير الحضور',
    'dashboard.absentChildren': 'الأطفال الغائبون',
    'dashboard.absentChildrenDesc': 'عرض وإبلاغ أولياء الأمور عن الأطفال الغائبين',
    'dashboard.manageRoles': 'إدارة الأدوار',
    'dashboard.manageRolesDesc': 'تعيين وإدارة أدوار المستخدمين',
    'dashboard.qrCodes': 'رموز QR',
    'dashboard.qrCodesDesc': 'إنشاء رموز QR للأطفال',
    'dashboard.scanQR': 'مسح QR',
    'dashboard.scanQRDesc': 'مسح رموز QR لتسجيل الحضور',
    'dashboard.myChildren': 'أطفالي',
    'dashboard.myChildrenDesc': 'عرض معلومات أطفالك',
    'dashboard.attendanceHistory': 'سجل الحضور',
    'dashboard.attendanceHistoryDesc': 'عرض سجلات حضور أطفالك',
    'dashboard.servantAttendance': 'حضور الخدام',
    'dashboard.servantAttendanceDesc': 'تسجيل حضور الخدام',
    
    // Children
    'children.title': 'إدارة الأطفال',
    'children.addNew': 'إضافة طفل جديد',
    'children.editChild': 'تعديل الطفل',
    'children.noChildren': 'لم يتم العثور على أطفال',
    'children.fullName': 'الاسم الكامل',
    'children.dateOfBirth': 'تاريخ الميلاد',
    'children.parentName': 'اسم ولي الأمر',
    'children.parentPhone': 'هاتف ولي الأمر',
    'children.address': 'العنوان',
    'children.schoolGrade': 'الصف الدراسي',
    'children.attendanceStatus': 'حالة الحضور',
    'children.assignedServant': 'الخادم المعين',
    'children.selectServant': 'اختر خادم',
    'children.noServant': 'لا يوجد خادم معين',
    'children.formDescription': 'أدخل معلومات الطفل أدناه',
    'children.regular': 'منتظم',
    'children.irregular': 'غير منتظم',
    'children.new': 'جديد',
    'children.confirmDelete': 'هل أنت متأكد أنك تريد حذف هذا الطفل؟',
    
    // Servants
    'servants.title': 'إدارة الخدام',
    'servants.noServants': 'لم يتم العثور على خدام',
    
    // Servant Attendance
    'servantAttendance.title': 'حضور الخدام',
    'servantAttendance.subtitle': 'تسجيل حضور الخدام',
    'servantAttendance.selectDate': 'اختر تاريخ الخدمة',
    'servantAttendance.presentCount': 'حاضرون',
    'servantAttendance.absentCount': 'غائبون',
    'servantAttendance.totalCount': 'إجمالي الخدام',
    'servantAttendance.saveSuccess': 'تم حفظ حضور الخدام بنجاح',
    'servantAttendance.saveError': 'فشل في حفظ حضور الخدام',
    'servantAttendance.loadError': 'فشل في تحميل الخدام',
    'servantAttendance.noServants': 'لا يوجد خدام مسجلون',
    
    // Attendance
    'attendance.title': 'الحضور',
    'attendance.selectDate': 'اختر التاريخ',
    'attendance.recordedBy': 'سجّل بواسطة',
    'attendance.markPresent': 'تسجيل حضور',
    'attendance.markAbsent': 'تسجيل غياب',
    'attendance.alreadyRecorded': 'تم تسجيل الحضور مسبقاً',
    'attendance.saveSuccess': 'تم حفظ الحضور بنجاح',
    'attendance.saveError': 'فشل في حفظ الحضور',
    'attendance.presentCount': 'حاضرون',
    'attendance.absentCount': 'غائبون',
    'attendance.totalCount': 'الإجمالي',
    
    // Reports
    'reports.title': 'التقارير والإحصائيات',
    'reports.generate': 'إنشاء تقرير',
    'reports.dateRange': 'نطاق التاريخ',
    'reports.startDate': 'تاريخ البداية',
    'reports.endDate': 'تاريخ النهاية',
    'reports.totalChildren': 'إجمالي الأطفال',
    'reports.registeredInSystem': 'المسجلين في النظام',
    'reports.averageAttendance': 'متوسط الحضور',
    'reports.acrossAllChildren': 'لجميع الأطفال',
    'reports.totalRecords': 'إجمالي السجلات',
    'reports.attendanceRecords': 'سجلات الحضور',
    'reports.individualStats': 'إحصائيات الحضور الفردية',
    'reports.detailedBreakdown': 'تفصيل الحضور لكل طفل',
    'reports.childName': 'اسم الطفل',
    'reports.totalServices': 'إجمالي الخدمات',
    'reports.attended': 'حضر',
    'reports.attendanceRate': 'نسبة الحضور',
    'reports.noData': 'لا توجد بيانات حضور بعد',
    'reports.loadError': 'فشل في تحميل التقارير',
    
    // Absent Children
    'absentChildren.title': 'تقرير الأطفال الغائبين',
    'absentChildren.subtitle': 'عرض وإبلاغ أولياء الأمور عن الأطفال الغائبين',
    'absentChildren.allAttended': 'جميع الأطفال حضروا في هذا التاريخ',
    'absentChildren.absentCount': 'أطفال غائبون',
    'absentChildren.noAbsent': 'لا يوجد أطفال غائبون في هذا التاريخ',
    'absentChildren.sendWhatsApp': 'إرسال واتساب إلى',
    'absentChildren.parents': 'أولياء الأمور',
    'absentChildren.sending': 'جاري الإرسال...',
    'absentChildren.childName': 'اسم الطفل',
    'absentChildren.parentName': 'اسم ولي الأمر',
    'absentChildren.parentPhone': 'هاتف ولي الأمر',
    'absentChildren.noPermission': 'ليس لديك صلاحية الوصول لهذه الصفحة',
    'absentChildren.loadError': 'فشل في تحميل الأطفال الغائبين',
    'absentChildren.notifySuccess': 'تم إرسال إشعارات الواتساب بنجاح',
    'absentChildren.notifyPartialError': 'فشل في إرسال بعض الإشعارات',
    'absentChildren.noChildren': 'لا يوجد أطفال غائبون للإبلاغ عنهم',
    
    // Child Report
    'childReport.title': 'تقرير ملف الطفل',
    'childReport.generatedOn': 'تم الإنشاء في',
    'childReport.personalInfo': 'المعلومات الشخصية',
    'childReport.fullName': 'الاسم الكامل',
    'childReport.dateOfBirth': 'تاريخ الميلاد',
    'childReport.yearsOld': 'سنة',
    'childReport.schoolGrade': 'الصف الدراسي',
    'childReport.notSpecified': 'غير محدد',
    'childReport.status': 'الحالة',
    'childReport.active': 'نشط',
    'childReport.address': 'العنوان',
    'childReport.parentName': 'اسم ولي الأمر',
    'childReport.parentPhone': 'هاتف ولي الأمر',
    'childReport.registrationDate': 'تاريخ التسجيل',
    'childReport.generalNotes': 'ملاحظات عامة',
    'childReport.attendanceSummary': 'ملخص الحضور',
    'childReport.totalSessions': 'إجمالي الجلسات',
    'childReport.attendanceHistory': 'سجل الحضور',
    'childReport.noRecords': 'لا توجد سجلات حضور',
    'childReport.endOfReport': 'نهاية التقرير',
    'childReport.print': 'طباعة',
    'childReport.exportPDF': 'تصدير PDF',
    'childReport.backToChildren': 'العودة للأطفال',
    'childReport.notFound': 'الطفل غير موجود',
    'childReport.loadingReport': 'جاري تحميل التقرير...',
    'childReport.loadError': 'فشل في تحميل تقرير الطفل',
    'childReport.exportHint': 'استخدم طباعة > حفظ كـ PDF لتصدير التقرير',
    
    // Manage Roles
    'manageRoles.title': 'إدارة أدوار المستخدمين',
    'manageRoles.subtitle': 'تعيين الأدوار للمستخدمين للتحكم في مستوى وصولهم',
    'manageRoles.roleDescriptions': 'وصف الأدوار:',
    'manageRoles.adminDesc': 'وصول كامل لجميع المميزات',
    'manageRoles.servantDesc': 'يمكنه إدارة الأطفال المعينين وتسجيل الحضور',
    'manageRoles.parentDesc': 'يمكنه عرض معلومات وحضور طفله',
    'manageRoles.currentRole': 'الدور الحالي',
    'manageRoles.changeRole': 'تغيير الدور',
    'manageRoles.noRole': 'بدون دور',
    'manageRoles.noUsers': 'لا يوجد مستخدمون',
    'manageRoles.roleUpdated': 'تم تحديث الدور بنجاح',
    'manageRoles.roleRemoved': 'تم إزالة الدور بنجاح',
    'manageRoles.updateError': 'تعذر تحديث الدور. حاول مرة أخرى.',
    'manageRoles.loadError': 'تعذر تحميل المستخدمين. قم بتحديث الصفحة.',
    'manageRoles.adminOnly': 'فقط المسؤولون يمكنهم إدارة الأدوار',
    'manageRoles.manualSetup': 'الإعداد اليدوي (طريقة بديلة)',
    'manageRoles.manualSetupDesc': 'إذا كنت بحاجة لتعيين الأدوار يدوياً عبر الخادم',
    
    // QR
    'qr.title': 'رموز QR',
    'qr.generate': 'إنشاء رمز QR',
    'qr.download': 'تحميل',
    'qr.print': 'طباعة',
    'qr.scanTitle': 'ماسح QR',
    'qr.scanInstructions': 'وجّه الكاميرا نحو رمز QR للمسح',
    'qr.scanSuccess': 'تم تسجيل الحضور بنجاح',
    'qr.scanError': 'خطأ في مسح رمز QR',
    
    // Roles
    'roles.title': 'إدارة الأدوار',
    'roles.admin': 'مسؤول',
    'roles.servant': 'خادم',
    'roles.parent': 'ولي أمر',
    'roles.none': 'بدون دور',
    'roles.assignRole': 'تعيين دور',
    'roles.currentRole': 'الدور الحالي',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
